### ISSUE TITLE
Bifunctor support?

### ISSUE THREAD

**Issue by hasufell** [jberryman/directory-tree#7]
I've been playing with this library to create some sort of filemanager. The idea was to read the directories lazily and stuff all possible information I could ever need into the `a` field of `DirTree a`.

The problem is, that this doesn't really allow me to save information for the directories. So I came up with my own data type to extend it:
```hs
data AnchoredDirTree a b =
  (:/) { anchor :: FilePath, dirTree :: DirTree a b }
  deriving (Show, Ord, Eq)


data DirTree a b =
    Failed {
        name :: FileName
      , err  :: IOException
    }
  | Dir {
        name     :: FileName
      , contents :: [DirTree a b]
      , dir      :: a
    }
  | File {
        name :: FileName
      , file :: b
  } deriving Show
```

And then wrote a few Bifunctor instances and adjusted the rest of the functions, which seemed fairly straight forward, see this gist: https://gist.github.com/hasufell/f15de337f763570b2adf

Would it make sense to provide this sort of data structure in this library, maybe under a separate module?

**Comment by jberryman** [comment]
Yeah, I definitely understand your use case. A possibly better (in the context of the library) way to do this might be to change `Dir` to:

      | Dir {
            dir     :: a      -- formerly `name :: FileName`
          , contents :: [DirTree a b]
        }

And this could mirror our functions that already work on and manipulate `DirTree FileName`, which would instead work on `DirTree FileName FileName`.

Then we might want to simply remove the records (since those partial records aren't very nice). And add a function (a shim for users of `name`):

    name :: DirTree FileName a -> FileName

And I think rather than a `BiFunctor` instance, we might provide a newtype wrapper like:

    -- not a great name:
    newtype DirectoryView files dirs = DirectoryView (DirTree dirs files)

And provide all the relevant instances we can for that type.

Let me know what you think and let's stew on this for a bit.

**Comment by hasufell** [comment]
That sounds interesting, but I have two thoughts about that:
* about `name :: DirTree FileName a -> FileName`: I'd go so far to consider making `FileName` a newtype (API breakage :/ )... because it is just `String` and our `dir` record can have Strings of arbitrary meaning and isn't as explicit as the previous `name :: FileName` record anymore
* I'm not entirely sure if this wouldn't limit the API for my use case (and possibily others), since  any library function that wants to operate on directory and file names, must have the type `DirTree FileName FileName` type if I am not mistaken? Then people would have to create wrappers around those functions if they want to use it, because their types might be different, since they want to use the `dir :: a` record for something else. I think the `dropTo` function for example would be affected by this.

**Comment by jberryman** [comment]
`dropTo` would have the type

    dropTo :: FileName -> AnchoredDirTree Filename a -> Maybe Filename (AnchoredDirTree a)

other functions could be polymorphic in that new first variable.
